services:
  - type: web
    name: fifa-worldcup-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker api.main:app --bind 0.0.0.0:$PORT --workers 2
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4

  - type: web
    name: fifa-worldcup-frontend
    env: static
    plan: free
    buildCommand: cd fronted && npm install && npm run build
    staticPublishPath: fronted/dist
    envVars:
      - key: VITE_API_URL
        value: https://fifa-worldcup-api.onrender.com
